gameofthronesdjango/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('wiki/', include('wiki.urls')),
]

wiki/urls.py
from django.urls import path, re_path
from . import views

app_name = 'wiki'

urlpatterns = [
    # '/'
    re_path(r'^$',views.index, name='index'),

    # '/<id>'
    re_path(r'^(?P<house_id>[0-9]+)/$',views.detail, name='detail')

]

episodes/models.py
from django.db import models

# Create your models here.

gallery/models.py
from django.db import models

# Create your models here.

wiki/models.py
from django.db import models

# Create your models here.

class House(models.Model):
    house_name = models.CharField(max_length = 100)
    banner = models.CharField(max_length = 500)
    current_ruler = models.CharField(max_length = 100)
    slogan = models.CharField(max_length = 200)
    sigil = models.CharField(max_length = 200)
    founder = models.CharField(max_length = 100)
    region = models.CharField(max_length = 50)
    religion = models.CharField(max_length = 50)
    description = models.CharField(max_length = 4000)

    def __str__(self):
        return self.house_name + ' - ' + self.slogan

class Character(models.Model):
    house = models.ForeignKey(House, on_delete=models.CASCADE)
    name = models.CharField(max_length = 100)
    age = models.IntegerField()
    photo = models.CharField(max_length = 1000)
    alive = models.BooleanField(default = True)
    title = models.CharField(max_length = 100)
    portrayed_by = models.CharField(max_length = 100)
    description = models.CharField(max_length = 4000)

    def __str__(self):
        return self.name + ' of House ' + self.house.house_name

episodes/views.py
from django.shortcuts import render

# Create your views here.

gallery/views.py
from django.shortcuts import render

# Create your views here.

wiki/views.py
from django.shortcuts import render, get_object_or_404
from .models import House, Character

def index(request):
    houses = House.objects.all()
    return render(request, 'wiki/index.html', {'houses': houses})

def detail(request, house_id):
    house = get_object_or_404(House, pk=house_id)
    return render(request, 'wiki/detail.html', {'house': house,})

wiki/templates/wiki/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    {% load staticfiles %}
    <title>Game of Thrones -{% block title %} Wiki {% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'wiki/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="{% static 'wiki/js/main.js' %}"></script>
  </head>
  <body>
  <nav class="navbar navbar-inverse">
      <div class="container-fluid">

          <!-- Header -->
          <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="{% url 'wiki:index' %}">GameofThrones</a>
          </div>

          <!-- Items -->
          <div class="collapse navbar-collapse" id="topNavBar">
              <ul class="nav navbar-nav">
                  <li class="{% block houses_active %}{% endblock %}"><a href="#"><span class="glyphicon glyphicon-flag" aria-hidden="true"></span>&nbsp; Houses</a></li>
                  <li class="{% block characters_active %}{% endblock %}"><a href="#"><span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp; Characters</a></li>
                  <li class="{% block gallery_active %}{% endblock %}"><a href="#"><span class="glyphicon glyphicon-camera" aria-hidden="true"></span>&nbsp; Episodes</a></li>
                  <li class="{% block episodes_active %}{% endblock %}"><a href="#"><span class="glyphicon glyphicon-play" aria-hidden="true"></span>&nbsp; Gallery</a></li>
                  <li class="{% block about_active %}{% endblock %}"><a href="#"><span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>&nbsp; About</a></li>
              </ul>
              <form class="navbar-form navbar-left" role="search" method="get" action="#">
                  <div class="form-group">
                      <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
                  </div>
                  <button type="submit" class="btn btn-default">Search</button>
              </form>
              <ul class="nav navbar-nav navbar-right">
                  <li>
                      <a href="#">
                          <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Info
                      </a>
                  </li>
                  <li>
                      <a href="#">
                          <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                      </a>
                  </li>
              </ul>
          </div>

      </div>
  </nav>
  {% block body %}
  {% endblock %}
  </body>
</html>

wiki/templates/wiki/detail.html
{% extends 'wiki/base.html' %}
{% block title %}{{ house }}{% endblock %}
{% block house_active %}active{% endblock %}

{% block body %}
<div class="container-fluid songs-container">

    <div class="row">

        <!-- Left House Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="{% url 'wiki:detail' house.id %}">
                        {% if house.banner %}
                            <img src="{{ house.banner.url }}" class="img-responsive">
                        {% else %}
                            <h3>No image to display</h3>
                        {% endif %}
                    </a>
                    <h1>{{ house.house_name }} <small>{{ house.slogan }}</small></h1>
                    <h2>{{ house.current_ruler }}</h2>
                </div>
            </div>
        </div>

        <!-- Right Characters Info -->
        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" class="active"><a href="#">View All</a></li>
                <li role="presentation"><a href="#">Add New Song</a></li>
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">

                    <h3>All Characters</h3>

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                    <table class="table">
                        <thead>
                        <tr>
                            <th>Title</th>
                            <th>Audio File</th>
                            <th>Favorite</th>
                            <th>Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for song in album.song_set.all %}
                            <tr>
                                <td>{{ song.song_title }}</td>
                                <td>
                                    <a target="_blank" href="{{ song.audio_file.url }}">
                                        <button type="button" class="btn btn-success btn-xs">
                                            <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                        </button>
                                    </a>
                                </td>
                                <td>
                                    <a href="#" class="btn-favorite"><span class="glyphicon glyphicon-star {% if song.is_favorite %}active{% endif %}"></span></a>
                                </td>
                                <td>
                                    <form action="#" method="post" style="display: inline;">
                                        {% csrf_token %}
                                        <input type="hidden" name="song_id" value="{{ song.id }}" />
                                        <button type="submit" class="btn btn-danger btn-xs">
                                            <span class="glyphicon glyphicon-remove"></span>&nbsp; Delete
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>

                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}

wiki/templates/wiki/index.html
{% extends 'wiki/base.html' %}
{% block title %} Houses {% endblock %}
{% block houses_active %}active{% endblock %}

{% block body %}
<div class="houses-container container-fluid">

    <!-- Albums -->
    <div class="row">
        <div class="col-sm-12">
            <h3>{{ user.username }}'s Houses</h3>
        </div>
        {% if houses %}
            {% for house in houses %}
                <div class="col-sm-4 col-lg-2">
                    <div class="thumbnail">
                        <a href="{% url 'wiki:detail' house.id %}">
                            <img src="{{ house.banner.url }}" >
                        </a>
                        <div class="caption">
                            <h2>{{ house.house_name }}</h2>
                            <h4>{{ house.slogan }}</h4>

                            <!-- View Details -->
                            <a href="{% url 'wiki:detail' house.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>

                            <!-- Delete Album -->
                            <form action="#" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="house_id" value="{{ house.id }}" />
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </form>

                            <!-- Favorite Album -->
                            <a href="#" class="btn btn-default btn-sm btn-favorite" role="button">
                                <span class="glyphicon glyphicon-star {% if house.is_favorite %}active{% endif %}"></span>
                            </a>

                        </div>
                    </div>
                </div>
                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
            {% endfor %}
        {% else %}
            <div class="col-sm-12">
                <br>
                <a href="#}">
                    <button type="button" class="btn btn-success">
                        <span class="glyphicon glyphicon-plus"></span>&nbsp; Add a House
                    </button>
                </a>
            </div>
        {% endif %}
    </div>

    <!-- If user searches and there are songs -->
    {% if characters %}
        <div class="row">
            <div class="col-sm-12">
                <h3>Songs</h3>
            </div>
            <div class="col-sm-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Song Title</th>
                                    <th>Artist</th>
                                    <th>Audio File</th>
                                    <th>Album</th>
                                    <th>Favorite</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for song in songs %}
                                    <tr>
                                        <td>{{ song.song_title }}</td>
                                        <td>{{ song.album.artist }}</td>
                                        <td>
                                            <a target="_blank" href="{{ song.audio_file.url }}">
                                                <button type="button" class="btn btn-success btn-xs">
                                                    <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                                </button>
                                            </a>
                                        </td>
                                        <td>
                                            <a href="{% url 'music:detail' song.album.id %}">
                                                <img src="{{ song.album.album_logo.url }}" class="img-responsive" style="width: 20px; float: left; margin-right: 10px;" />
                                            </a>
                                            <a href="{% url 'music:detail' song.album.id %}">{{ song.album.album_title }}</a>
                                        </td>
                                        <td>
                                            <a href="{% url 'music:favorite' song.id %}" class="btn-favorite"><span class="glyphicon glyphicon-star {% if song.is_favorite %}active{% endif %}"></span></a>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}

</div>
{% endblock %}